### PR TITLE
reporter lock + move submission func + clarify imports

### PR DESCRIPTION
**Pull request by tallywiesenberg**
* interval reporter doesnt submit if the address is locked in the reporter 
* test submission function revamped and standardized. for testing different feeds, import `reporter_submit_once` from tests/conftest.py
* imports of `telliot_ampl_feeds` clarify if they reference the directory in `src` or the directory of the same name in `tests`

feedback very much welcome! also not pasing tox right now because of a packaging blocker with `telliot-core`

### CODE REVIEW

**Comment by tallywiesenberg** [comment]
> Top level scripts should be python scripts (which are cross-platform) instead of shell scripts.

I agree. We've written shell scripts in interim for ease of use for spuddy to run.

**Comment by tallywiesenberg** [comment]
> Like above, we should not import from `src`

Fair enough. I did this because there is a directory of the name `telliot_feed_examples` in both `src` and `tests`, which breaks the imports. i will rename `tests/telliot_feed_examples` to `tests/test_telliot_feed_examples`. or would you recommend something more pythonic?

**Comment by oraclown** [comment]
> This should be reverted. `src` should not be in the namespace if the package is properly installed.

Removed imports from `src.blah.blah...`

**Comment by oraclown** [comment]
> Top level scripts should be python scripts (which are cross-platform) instead of shell scripts.

removed bash scripts

**Comment by oraclown** [comment]
Reused docs from telliot-core. Can be changed in separate PR.
Updated `setup.cfg`, but I still can't get pytest to work by itself, only with tox can it import `telliot_core` stuff.

Changed the directory structure to something that I think makes more sense.
```
telliot_feed_examples
├── __init__.py
├── __main__.py
├── config
│   ├── __init__.py
│   └── ampl.py
├── feeds
│   ├── __init__.py
│   ├── ampl_usd_vwap_feed.py
│   ├── btc_usd_feed.py
│   └── uspce_feed.py
├── reporters
│   ├── __init__.py
│   ├── ampl_usd_vwap.py
│   └── interval.py
├── sources
│   ├── __init__.py
│   ├── ampl_usd_vwap.py
│   ├── bittrex.py
│   ├── coinbase.py
│   ├── coingecko.py
│   ├── gemini.py
│   ├── price_aggregator.py
│   └── uspce.py
└── utils
    ├── __init__.py
    └── profitcalc.py
```

Feedback welcome!

**Pull request merged**
