### PR TITLE
catch bad requests in WebPriceService class

### LINKED ISSUE #182: Bug
Log (running on mumbai)
```
Traceback (most recent call last):
  File "/home/ubuntu/tenv_dev/bin/telliot-examples", line 8, in <module>
    sys.exit(cli())
  File "/home/ubuntu/tenv_dev/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/tenv_dev/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/tenv_dev/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/tenv_dev/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/tenv_dev/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/tenv_dev/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ubuntu/tenv_dev/lib/python3.9/site-packages/telliot_core/cli/utils.py", line 18, in wrapper
    return asyncio.run(f(*args, **kwargs))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/ubuntu/tenv_dev/lib/python3.9/site-packages/telliot_feed_examples/cli.py", line 414, in report
    _, _ = await reporter.report()
  File "/home/ubuntu/tenv_dev/lib/python3.9/site-packages/telliot_feed_examples/reporters/interval.py", line 470, in report
    _, _ = await self.report_once()
  File "/home/ubuntu/tenv_dev/lib/python3.9/site-packages/telliot_feed_examples/reporters/interval.py", line 351, in report_once
    await datafeed.source.fetch_new_datapoint()
  File "/home/ubuntu/tenv_dev/lib/python3.9/site-packages/telliot_feed_examples/sources/price_aggregator.py", line 83, in fetch_new_datapoint
    datapoints = await self.update_sources()
  File "/home/ubuntu/tenv_dev/lib/python3.9/site-packages/telliot_feed_examples/sources/price_aggregator.py", line 69, in update_sources
    inputs = await gather_inputs()
  File "/home/ubuntu/tenv_dev/lib/python3.9/site-packages/telliot_feed_examples/sources/price_aggregator.py", line 64, in gather_inputs
    datapoints = await asyncio.gather(
  File "/home/ubuntu/tenv_dev/lib/python3.9/site-packages/telliot_core/pricing/price_source.py", line 32, in fetch_new_datapoint
    datapoint = await self.service.get_price(self.asset, self.currency)
  File "/home/ubuntu/tenv_dev/lib/python3.9/site-packages/telliot_feed_examples/sources/price/spot/gemini.py", line 60, in get_price
    r = GeminiPriceResponse.parse_obj(d["response"])
  File "pydantic/main.py", line 511, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 4 validation errors for GeminiPriceResponse
bid
  field required (type=value_error.missing)
ask
  field required (type=value_error.missing)
last
  field required (type=value_error.missing)
volume
  field required (type=value_error.missing)
```

### PR DESCRIPTION
**Pull request by tallywiesenberg**
closes #182 

get requests with python `requests` library returns a message, even if the http request was unsuccessful. This update catches bad requests in the WebPriceService class. This will prevent telliot from crashing on an unsuccessful API request.

Tested on the GeminiPriceService to match #182

### CODE REVIEW

**Comment by tallywiesenberg** [comment]
Ah, this is the wrong repository for this PR. I made the updates in telliot-core. But I will keep this PR open for the tests.

**Review by oraclown — CHANGES_REQUESTED** [review]
Nice, thanks for pushing this.

Looks like there's more GasPrice oracle changes in here than changes to fix the linked issue. Not sure if you meant to include those here.

Also, I think the fix needed for the bug @Spuddyminer reported is just error handling in `GeminiSpotPriceSource` for the line where it tries to parse the response. Since it's returning a valid `Response` object, but not the expected one (`GeminiPriceResponse`):
```python
r = GeminiPriceResponse.parse_obj(d["response"])
```
Handle the specific error from the issue probably: `pydantic.error_wrappers.ValidationError` and then catch any others and log those so the reporter doesn't stop.

**Comment by tallywiesenberg** [comment]
> 

1. Ah yeah the gas price oracle pushes were accidental. I'll reset those changes on the branch.
2. I see what you're saying...I added the telliot-core changes to catch bad responses (non 2xx responses), so that should help, but we should def catch the pydantic exception as well. I'll add a catch clause to the PR

**Comment by tallywiesenberg** [comment]
1. Ah I saw that the gas prices changes were merged into main, so I left them unchanged here
2. I added a catch clause for the pydantic `ValidationError`

**Review by oraclown — APPROVED** [review]
Nice

**Review by oraclown — APPROVED** [review]

**Pull request merged**
