### PR TITLE
Moved from StakerList to ChainedAccounts for account management.

### PR DESCRIPTION
**Pull request by clamdad**
Completed integration with core update here:
- [Replace StakerList config with encrypted keys using ChainedAccounts](https://github.com/tellor-io/telliot-core/pull/203)

### CODE REVIEW

**Review by oraclown — CHANGES_REQUESTED** [review]
Needs some things fixed before merge:
- [ ] Use same account object for life of the reporter, bc now it keeps asking for the password, defeating purpose of having an auto-reporter
- [ ] Exit or ask again if user enters wrong password

**Comment by clamdad** [comment]
> Needs some things fixed before merge:
> 
> * [ ]  Use same account object for life of the reporter, bc now it keeps asking for the password, defeating purpose of having an auto-reporter
> * [ ]  Exit or ask again if user enters wrong password

The CLI was unlocking the wrong account object.  This might have caused both problems.  Reporter is in lock gain, so need to wait to test.

**Comment by oraclown** [comment]
> > Needs some things fixed before merge:
> > 
> > * [x]   Use same account object for life of the reporter, bc now it keeps asking for the password, defeating purpose of having an auto-reporter
> > * [x]   Exit or ask again if user enters wrong password
> 
> The CLI was unlocking the wrong account object. This might have caused both problems. Reporter is in lock gain, so need to wait to test.

I pulled down your changes and it still asks for password twice. If it doesn't ask again after reporting once, then that's fine probably

**Comment by clamdad** [comment]
This issue was only happening if the `-st` flag was used.  Looks like when we call `tellorflex = core.get_tellorflex_contracts()`
it was getting a new one ignores the one that is unlocked outside of the telliot-core context.

The real issue was that `reporter_cli_core` and `cli_core` context getters were looking for 'ACCOUNT_NAME` instead of `STAKER_TAG` in the context.    

Now that the core context is being set correctly, you can use `core.get_account()` as usual to get the correct configured account (including the one specified on the command line).

So I replaced the instances of staker_tag with account_name, which also changes the CLI flag.  

Hope it works!

**Review by oraclown — COMMENTED** [review]
Nice, look good. Will test in a moment..

**Comment by oraclown** [comment]
> Nice, look good. Will test in a moment..

Success!

**Comment by oraclown** [comment]
> Needs some things fixed before merge:
> 
> * [x]  Use same account object for life of the reporter, bc now it keeps asking for the password, defeating purpose of having an auto-reporter
> * [x]  Exit or ask again if user enters wrong password

Resolved

**Pull request merged**
