### PR TITLE
Add Flashbots and EIP-1559 transaction type support, more CLI options

### PR DESCRIPTION
**Pull request by oraclown**
(***** 12/29/21 UPDATE *****) please see more recent comments for current status

This is a work-in-progress. I haven't been able to get tx receipts after submitting bundles.

Tests will fail because Python [flashbots](https://github.com/flashbots/web3-flashbots) uses a previous version of web3 without a lot of functionality that `telliot-core` and `telliot-examples` currently use.

### CODE REVIEW

**Comment by oraclown** [comment]
Run this script like so: `python src/telliot_feed_examples/report_with_flashbots.py`

Before that you'll need to edit lines 124-137 on contract.py in your `telliot-core` dependency to be:
```python
# # Confirm transaction
# tx_receipt = self.node.web3.eth.wait_for_transaction_receipt(
#     tx_hash, timeout=360
# )

# Point to relevant explorer
logger.info(
           f"""View reported data: \n
           {self.node.explorer}/tx/{tx_hash.hex()}
           """
       )

# return tx_receipt, status
return tx_hash, status
```

Because the `web3` version that `flashbots` uses doesn't have that method.

Also, edit `provider.py` in your `flashbots` dependency to use the Goerli flashbots relay on line 16:
```python
os.environ.get("FLASHBOTS_HTTP_PROVIDER_URI", "https://relay-goerli.flashbots.net/")
```

Add this to your `endpoints.yaml` in Telliot configs and update your API key:
```yaml
- type: RPCEndpoint
  chain_id: 5
  network: goerli
  provider: Infura
  url: https://goerli.infura.io/v3/*****
  explorer: https://goerli.etherscan.io
  ```

And finally, change `chain_id` in `main.yaml` to be `5` for the Goerli endpoint.

**Comment by oraclown** [comment]
## Some overall updates:
Keep in mind that this branch is a major work-in-progress. Things can break and you might lose money! Also, many tests have been skipped because of breaking changes.
- Removes some legacy transaction gas price info CLI commands
- Removes chain id, private key, and rpc url overrite commands
- Adds option to choose staker by providing tag (this is why some above cmds were removed)
- Updates expected profit CLI flag to not skip check on break-even
- Only supports submitting values using flashbots and type 2 transactions (EIP-1559)
- Currently breaks `report_once` and `report` methods of `IntervalReporter`
- Creates a `FlashbotsReporter` which inherits from `IntervalReporter`

### How to submit using flashbots:
Three steps:

1. Create a new signatory account on Metamask just like you create any other account. This shouldn't store any funds or anything. Retrieve the private key (example: `abcd1234*****`).
2. Create a `.env` file in the home directory of this project and add the following variable to it: `SIGNATURE_PRIVATE_KEY=abcd1234****`.
3. Report using the CLI. Make sure you specify a reporting account that's staked on mainnet. Example: `telliot-examples --staker-tag my-mainnet-staker-tag --flashbots report -gl 310000 -p 7`.

**Comment by oraclown** [comment]
## Updates:

- Sends txs to Flashbots relay by default, since sending to public mempool not currently supported.
- Adds ability to use type 0 (legacy) and type 2 (EIP-1559) transactions using flag: `-tx/--tx-type`.
- By default any fee info not provided via CLI flags (`max_fee`, `priority_fee`, or `legacy_gas_price`) will be fetched from free APIs (etherscan and ethgasstation).
- Bypass profit check by passing "YOLO" for `expected_profit` CLI flag.

## Usage:
```
telliot-examples -st my-mainnet-acct report -tx 0 -p YOLO
```

## Sample output:
```
⚡🤖⚡ Reporting through Flashbots relay ⚡🤖⚡
Reporting legacy ID: 1
Current chain ID: 1
🍜🍜🍜 Reporter not enforcing profit threshold! 🍜🍜🍜
Transaction type: 0
Gas Limit: 350000
Legacy gas price (gwei): None
Max fee (gwei): None
Priority fee (gwei): None
Gas price speed: fast

Press [ENTER] to confirm settings.
```

**Comment by tkernell** [comment]
telliot-core 0.0.8.dev1
telliot_feed_examples (plugin): Version 0.0.9dev0
connected: eth-mainnet [staker: my_green_staker]

⚡🤖⚡ Reporting through Flashbots relay ⚡🤖⚡
Reporting legacy ID: 1
Current chain ID: 1
🍜🍜🍜 Reporter not enforcing profit threshold! 🍜🍜🍜
Transaction type: 0
Gas Limit: 350000
Legacy gas price (gwei): None
Max fee (gwei): None
Priority fee (gwei): None
Gas price speed: fast

Press [ENTER] to confirm settings.
2021-12-29 17:25:37,186 - telliot_feed_examples.reporters.flashbot - INFO - Reporting with account: 0x67c290c74ef390F34Bf492cc0aF97408Cd6DA22D
2021-12-29 17:25:37,534 - telliot_feed_examples.reporters.interval - INFO - Stake status: 1
2021-12-29 17:25:37,626 - telliot_feed_examples.reporters.interval - INFO - Last submission timestamp: 1639433291
2021-12-29 17:25:38,615 - telliot_feed_examples.sources.price_aggregator - INFO - Running median on [3775.14, 3787.59, 3775.21, 3776.75, 3775.05]
2021-12-29 17:25:38,615 - telliot_feed_examples.sources.price_aggregator - INFO - Feed Price: 3775.21 reported at time 2021-12-29 17:25:38.615803+00:00
2021-12-29 17:25:38,616 - telliot_feed_examples.sources.price_aggregator - INFO - Running median on [34.13]
2021-12-29 17:25:38,616 - telliot_feed_examples.sources.price_aggregator - INFO - Feed Price: 34.13 reported at time 2021-12-29 17:25:38.616357+00:00
2021-12-29 17:25:38,884 - telliot_feed_examples.reporters.flashbot - INFO - 
                tips: 0.0 TRB
                time-based reward: 0.19 TRB
                gas limit: 350000
                legacy gas price: 147
                
2021-12-29 17:25:38,884 - telliot_feed_examples.reporters.flashbot - INFO - Estimated profit: $-187.75
2021-12-29 17:25:38,885 - telliot_feed_examples.reporters.flashbot - INFO - Estimated percent profit: -96.66%
2021-12-29 17:25:39,564 - telliot_feed_examples.sources.price_aggregator - INFO - Running median on [3775.38, 3787.59, 3775.21, 3776.75, 3775.05]
2021-12-29 17:25:39,565 - telliot_feed_examples.sources.price_aggregator - INFO - Feed Price: 3775.38 reported at time 2021-12-29 17:25:39.565020+00:00
Traceback (most recent call last):
  File "/home/ubuntu/telliot-lab/telliot-feed-examples/flashbots-env/bin/telliot-examples", line 33, in <module>
    sys.exit(load_entry_point('telliot-feed-examples', 'console_scripts', 'telliot-examples')())
  File "/home/ubuntu/telliot-lab/telliot-feed-examples/flashbots-env/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/telliot-lab/telliot-feed-examples/flashbots-env/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/telliot-lab/telliot-feed-examples/flashbots-env/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/telliot-lab/telliot-feed-examples/flashbots-env/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/telliot-lab/telliot-feed-examples/flashbots-env/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/telliot-lab/telliot-feed-examples/flashbots-env/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ubuntu/telliot-lab/telliot-feed-examples/src/telliot_feed_examples/cli.py", line 289, in report
    _, _ = asyncio.run(reporter.report())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/ubuntu/telliot-lab/telliot-feed-examples/src/telliot_feed_examples/reporters/flashbot.py", line 338, in report
    _, _ = await self.report_once()
  File "/home/ubuntu/telliot-lab/telliot-feed-examples/src/telliot_feed_examples/reporters/flashbot.py", line 301, in report_once
    self.endpoint._web3.flashbots.send_bundle(
  File "/home/ubuntu/telliot-lab/telliot-feed-examples/flashbots-env/lib/python3.8/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/home/ubuntu/telliot-lab/telliot-feed-examples/flashbots-env/lib/python3.8/site-packages/web3/manager.py", line 197, in request_blocking
    response = self._make_request(method, params)
  File "/home/ubuntu/telliot-lab/telliot-feed-examples/flashbots-env/lib/python3.8/site-packages/web3/manager.py", line 150, in _make_request
    return request_func(method, params)
  File "/home/ubuntu/telliot-lab/telliot-feed-examples/src/telliot_feed_examples/flashbots/middleware.py", line 41, in middleware
    return flashbots_provider.make_request(method, params)
  File "/home/ubuntu/telliot-lab/telliot-feed-examples/src/telliot_feed_examples/flashbots/provider.py", line 57, in make_request
    headers = self.get_request_headers() | {
TypeError: unsupported operand type(s) for |: 'dict' and 'dict'

**Comment by oraclown** [comment]
> telliot-core 0.0.8.dev1 telliot_feed_examples (plugin): Version 0.0.9dev0 connected: eth-mainnet [staker: my_green_staker]
> 
> ⚡🤖⚡ Reporting through Flashbots relay ⚡🤖⚡ Reporting legacy ID: 1 Current chain ID: 1 🍜🍜🍜 Reporter not enforcing profit threshold! 🍜🍜🍜 Transaction type: 0 Gas Limit: 350000 Legacy gas price (gwei): None Max fee (gwei): None Priority fee (gwei): None Gas price speed: fast
> 
> Press [ENTER] to confirm settings. 2021-12-29 17:25:37,186 - telliot_feed_examples.reporters.flashbot - INFO - Reporting with account: 0x67c290c74ef390F34Bf492cc0aF97408Cd6DA22D 2021-12-29 17:25:37,534 - telliot_feed_examples.reporters.interval - INFO - Stake status: 1 2021-12-29 17:25:37,626 - telliot_feed_examples.reporters.interval - INFO - Last submission timestamp: 1639433291 2021-12-29 17:25:38,615 - telliot_feed_examples.sources.price_aggregator - INFO - Running median on [3775.14, 3787.59, 3775.21, 3776.75, 3775.05] 2021-12-29 17:25:38,615 - telliot_feed_examples.sources.price_aggregator - INFO - Feed Price: 3775.21 reported at time 2021-12-29 17:25:38.615803+00:00 2021-12-29 17:25:38,616 - telliot_feed_examples.sources.price_aggregator - INFO - Running median on [34.13] 2021-12-29 17:25:38,616 - telliot_feed_examples.sources.price_aggregator - INFO - Feed Price: 34.13 reported at time 2021-12-29 17:25:38.616357+00:00 2021-12-29 17:25:38,884 - telliot_feed_examples.reporters.flashbot - INFO - tips: 0.0 TRB time-based reward: 0.19 TRB gas limit: 350000 legacy gas price: 147
> 
> 2021-12-29 17:25:38,884 - telliot_feed_examples.reporters.flashbot - INFO - Estimated profit: $-187.75 2021-12-29 17:25:38,885 - telliot_feed_examples.reporters.flashbot - INFO - Estimated percent profit: -96.66% 2021-12-29 17:25:39,564 - telliot_feed_examples.sources.price_aggregator - INFO - Running median on [3775.38, 3787.59, 3775.21, 3776.75, 3775.05] 2021-12-29 17:25:39,565 - telliot_feed_examples.sources.price_aggregator - INFO - Feed Price: 3775.38 reported at time 2021-12-29 17:25:39.565020+00:00 Traceback (most recent call last): File "/home/ubuntu/telliot-lab/telliot-feed-examples/flashbots-env/bin/telliot-examples", line 33, in sys.exit(load_entry_point('telliot-feed-examples', 'console_scripts', 'telliot-examples')()) File "/home/ubuntu/telliot-lab/telliot-feed-examples/flashbots-env/lib/python3.8/site-packages/click/core.py", line 1128, in **call** return self.main(*args, **kwargs) File "/home/ubuntu/telliot-lab/telliot-feed-examples/flashbots-env/lib/python3.8/site-packages/click/core.py", line 1053, in main rv = self.invoke(ctx) File "/home/ubuntu/telliot-lab/telliot-feed-examples/flashbots-env/lib/python3.8/site-packages/click/core.py", line 1659, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File "/home/ubuntu/telliot-lab/telliot-feed-examples/flashbots-env/lib/python3.8/site-packages/click/core.py", line 1395, in invoke return ctx.invoke(self.callback, **ctx.params) File "/home/ubuntu/telliot-lab/telliot-feed-examples/flashbots-env/lib/python3.8/site-packages/click/core.py", line 754, in invoke return __callback(*args, **kwargs) File "/home/ubuntu/telliot-lab/telliot-feed-examples/flashbots-env/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func return f(get_current_context(), *args, **kwargs) File "/home/ubuntu/telliot-lab/telliot-feed-examples/src/telliot_feed_examples/cli.py", line 289, in report _, _ = asyncio.run(reporter.report()) File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run return loop.run_until_complete(main) File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete return future.result() File "/home/ubuntu/telliot-lab/telliot-feed-examples/src/telliot_feed_examples/reporters/flashbot.py", line 338, in report _, _ = await self.report_once() File "/home/ubuntu/telliot-lab/telliot-feed-examples/src/telliot_feed_examples/reporters/flashbot.py", line 301, in report_once self.endpoint._web3.flashbots.send_bundle( File "/home/ubuntu/telliot-lab/telliot-feed-examples/flashbots-env/lib/python3.8/site-packages/web3/module.py", line 57, in caller result = w3.manager.request_blocking(method_str, File "/home/ubuntu/telliot-lab/telliot-feed-examples/flashbots-env/lib/python3.8/site-packages/web3/manager.py", line 197, in request_blocking response = self._make_request(method, params) File "/home/ubuntu/telliot-lab/telliot-feed-examples/flashbots-env/lib/python3.8/site-packages/web3/manager.py", line 150, in _make_request return request_func(method, params) File "/home/ubuntu/telliot-lab/telliot-feed-examples/src/telliot_feed_examples/flashbots/middleware.py", line 41, in middleware return flashbots_provider.make_request(method, params) File "/home/ubuntu/telliot-lab/telliot-feed-examples/src/telliot_feed_examples/flashbots/provider.py", line 57, in make_request headers = self.get_request_headers() | { TypeError: unsupported operand type(s) for |: 'dict' and 'dict'

Needs python 3.9 or above I believe

**Pull request merged**
